services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    ports:
      - "8989:80"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      db:
        condition: service_healthy
    networks:
      - laravel_network

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: worker
    restart: unless-stopped
    volumes:
      - ./backend:/var/www/html
    depends_on:
      db:
        condition: service_healthy
    networks:
      - laravel_network
    command: ["php", "artisan", "queue:work", "--tries=3", "--timeout=110", "--sleep=3"]

  db:
    image: mysql:8
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE:-university_agent}
    ports:
      - "3309:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${DB_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge

volumes:
  db_data:
